# Generated by Django 6.0.5 on 2026-05-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('PUJA', 'Puja Saman'), ('SHOES', 'Shoes Shop'), ('KAPRA', 'Kapra Shop'), ('SHRINGAR', 'Shringar Shop')], max_length=20)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
